name: 'Terraform Plan'
on: [push, pull_request]
defaults:
      run:
        shell: bash
        working-directory: ./terraform

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt -check

      - name: 'Terraform Plan'
        run: terraform plan
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS-REGION: us-east-1
          TFE_TOKEN: ${{ secrets.TF_API_TOKEN }}
