name: 'Terraform Execution'

on:
  push:
    branches:
      - master
      - develop
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: ./terraform

jobs:
  build:
    name: 'Terraform Lint and Plan'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: 'Terraform Init'
        run: terraform init
      - name: 'Terraform Format'
        run: terraform fmt -check
      - name: Check linting of Terraform files
        uses: devops-infration-tflint@master
        with:
          fail_on_changes: false
          tflint_params: "--deep"
      - name: 'Terraform Plan'
        run: terraform plan
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: 'Terraform Init'
        run: terraform init
      - name: 'Terraform Plan'
        run: terraform plan
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

#--------------------------------------------------------------------
# Disabled to avoid Terrraform being applied ($$$)
#--------------------------------------------------------------------
#     - name: 'Terraform Apply'
#       run: terraform apply -auto-approve
#       env:
#         AWS_DEFAULT_REGION: us-east-1
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
#--------------------------------------------------------------------


